DROP TABLE logs;

CREATE TABLE logs (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
tab_name VARCHAR(50),
id_id INT UNSIGNED NOT NULL,
name VARCHAR(255)
) ENGINE = Archive;