DELIMITER //

DROP FUNCTION IF EXISTS	time_now//

CREATE FUNCTION time_now ()
RETURNS VARCHAR(255) DETERMINISTIC
BEGIN
    CASE	
	WHEN DATE_FORMAT(CURRENT_TIME(), "%H" ) > 6 AND DATE_FORMAT(CURRENT_TIME(), "%H" ) < 13 
    THEN RETURN 'GOOD MORNING';
    WHEN DATE_FORMAT(CURRENT_TIME(), "%H" ) > 12 AND DATE_FORMAT(CURRENT_TIME(), "%H" ) < 19 
    THEN RETURN 'GOOD AFTERNOON';
    ELSE RETURN 'GOOD NIGHT';
    END CASE;
END//

SELECT time_now()//